### ISSUE TITLE
Обновление зависимостей `@atls/grpc-error-status`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/grpc#6]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by OsirisAnubiz** [comment]
Такая же ситтуация как [тут](https://github.com/atls/auth/issues/6#issuecomment-2402622958]

**Comment by OsirisAnubiz** [comment]
@Nelfimov не работает `yarn typecheck` просто бескочно крутиться, банд уже пытался обновить до последней версии, такая же ситтуация

**Comment by OsirisAnubiz** [comment]
### Статус на конец дня
- Так и не понял почему не работает `yarn typecheck`
  - удаление даже всех пакетов из `packages/grpc-error-status/package.json` не помогло
  - `skipLibCheck` тоже не помогло

### Осалось сделать
- Фактически даже не преступил к таске, т.к. не работает `yarn typecheck`, завтра буду ещё что-то пробовать, чтобы понять в чём ошибка, возможно есть какой-то файл, который проверяется хотя не должен и из-за этого ошибка возникает, хотя не уверен. Может что-то с `.yarn` не так, стоит с этим что-то попробовать

**Comment by Nelfimov** [comment]
скорее всего какой то из пакетов зависимостей имеет что-то что отправляет tsc в бесконечный луп.

Попробуй:
- раскидать везде skipLibCheck
- обвешать `@ts-ignore` все сорсы

**Comment by OsirisAnubiz** [comment]
Попробовал всё сверху, сейчас ищу в чём проблема

**Comment by OsirisAnubiz** [comment]
Наверно буду пока другие задачи закрывать, которые быстрее сделать

**Comment by OsirisAnubiz** [comment]
Статус на конец дня:
- пока поставил эту задачу на паузу и делаю другие таски. Не могу понять почему typecheck происходит бесконечно

**Comment by OsirisAnubiz** [comment]
Вообще не могу понять в чём проблема.
@Nelfimov есть возможность сделать `git commit` при этом, чтобы `yarn check` не происходил в новом бандле? Я хочу попробовать открыть PR и посмотреть пройдёт ли линт у гитхабовских экшенов, чтобы быть уверенным, что проблема не с моим окружением связанна.

**Comment by TorinAsakura** [comment]
@OsirisAnubiz добавь в конце ключ --no-verify

**Comment by OsirisAnubiz** [comment]
Проблема не связанна с моим окружением. В экшенах тоже `typecheck` не может выполниться

**Comment by OsirisAnubiz** [comment]
То что уже было попробано:
- skipLibCheck - не помогло
- @ts-ignore на все импорты - не помогло
- думал что возможно тайпчек пытается спарсить .yaml файлы удалил их - не помогло
- думал проблема в proto дирректории удалил - не помогло

Важно:
также не проходит `yarn build` и `yarn prepack` для пакета

**Comment by Nelfimov** [comment]
> * skipLibCheck - не помогло

Где ты это указал?

**Comment by OsirisAnubiz** [comment]
@Nelfimov
> Где ты это указал?

В `tsconfig.json`

**Comment by Nelfimov** [comment]
https://github.com/atls/nestjs/blob/224e79782eb40689123df52fa82ab426370b407e/package.json#L16

**Comment by OsirisAnubiz** [comment]
@Nelfimov помогло, спасибо огромное

**Comment by OsirisAnubiz** [comment]
Статус на конец дня:
- всё сделал, жду ревью

**Comment by OsirisAnubiz** [comment]
Статус:
- исправил на esm модули, жду ревью
